##非自定义属性
server:
  port: 8085 # 启动端口
spring:
  application:
    name: async-thread
##线程池属性
thread:
  pool:
    core-pool-size: 2
    max-pool-size: 5
    queue-capacity: 12
    keep-alive-seconds: 60
    thread-name-prefix: async-thread-
